"""add plato_nombre bebida_nombre to pedidos

Revision ID: 361943379f14
Revises: 537684b17622
Create Date: 2026-07-22 17:03:43.660083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361943379f14'
down_revision = '537684b17622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plato_nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bebida_nombre', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('bebida_nombre')
        batch_op.drop_column('plato_nombre')

    # ### end Alembic commands ###
