"""inicial con activo en dia_menu

Revision ID: 4d72abe4c691
Revises: 
Create Date: 2026-05-29 01:12:41.620460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d72abe4c691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.alter_column('plato_fuerte_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.alter_column('plato_fuerte_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
