"""descripcion en platillo

Revision ID: 4e09cdf5ffbf
Revises: 4d72abe4c691
Create Date: 2026-05-29 01:29:27.868151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e09cdf5ffbf'
down_revision = '4d72abe4c691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
