"""add nombre to menus_semanales

Revision ID: 537684b17622
Revises: ef031fd95b2a
Create Date: 2026-07-04 13:03:25.457864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537684b17622'
down_revision = 'ef031fd95b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_semanales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=128), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_semanales', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
