"""direcciones_cliente

Revision ID: 6fec8caf22c4
Revises: b9abb09e9790
Create Date: 2026-06-02 19:33:52.284460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fec8caf22c4'
down_revision = 'b9abb09e9790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=True),
    sa.Column('tipo_vivienda', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('referencias', sa.Text(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones_cliente')
    # ### end Alembic commands ###
