"""receptor y direccion en pedido

Revision ID: 7b328f02f2eb
Revises: bbd766eae4a1
Create Date: 2026-06-02 21:29:17.937486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b328f02f2eb'
down_revision = 'bbd766eae4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receptor_nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('receptor_telefono', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'direcciones_cliente', ['direccion_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receptor_telefono')
        batch_op.drop_column('receptor_nombre')
        batch_op.drop_column('direccion_id')

    # ### end Alembic commands ###
