"""multi seleccion platos fuertes alternativas guarniciones

Revision ID: aac3e73be391
Revises: c20a226fad24
Create Date: 2026-05-29 02:00:23.712780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac3e73be391'
down_revision = 'c20a226fad24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_alternativas',
    sa.Column('dia_menu_id', sa.Integer(), nullable=False),
    sa.Column('platillo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dia_menu_id'], ['dias_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dia_menu_id', 'platillo_id')
    )
    op.create_table('dia_guarniciones',
    sa.Column('dia_menu_id', sa.Integer(), nullable=False),
    sa.Column('platillo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dia_menu_id'], ['dias_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dia_menu_id', 'platillo_id')
    )
    op.create_table('dia_platos_fuertes',
    sa.Column('dia_menu_id', sa.Integer(), nullable=False),
    sa.Column('platillo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dia_menu_id'], ['dias_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dia_menu_id', 'platillo_id')
    )
    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dias_menu_alternativa_plato_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('dias_menu_plato_fuerte_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('dias_menu_guarnicion_id_fkey'), type_='foreignkey')
        batch_op.drop_column('guarnicion_id')
        batch_op.drop_column('plato_fuerte_id')
        batch_op.drop_column('alternativa_plato_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternativa_plato_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plato_fuerte_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('guarnicion_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('dias_menu_guarnicion_id_fkey'), 'platillos', ['guarnicion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('dias_menu_plato_fuerte_id_fkey'), 'platillos', ['plato_fuerte_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('dias_menu_alternativa_plato_id_fkey'), 'platillos', ['alternativa_plato_id'], ['id'])

    op.drop_table('dia_platos_fuertes')
    op.drop_table('dia_guarniciones')
    op.drop_table('dia_alternativas')
    # ### end Alembic commands ###
