"""add proteina to platillos

Revision ID: b8f129f8a8b6
Revises: 361943379f14
Create Date: 2026-07-22 17:35:23.092264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f129f8a8b6'
down_revision = '361943379f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proteina', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.drop_column('proteina')

    # ### end Alembic commands ###
