"""tipo_vivienda y referencias_entrega en user

Revision ID: b9abb09e9790
Revises: edbbe9135712
Create Date: 2026-06-01 19:23:36.761688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9abb09e9790'
down_revision = 'edbbe9135712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_vivienda', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('referencias_entrega', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('referencias_entrega')
        batch_op.drop_column('tipo_vivienda')

    # ### end Alembic commands ###
