"""estados confirmado rechazado y motivo_rechazo

Revision ID: bbd766eae4a1
Revises: 6fec8caf22c4
Create Date: 2026-06-02 20:24:00.292631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd766eae4a1'
down_revision = '6fec8caf22c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_rechazo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('motivo_rechazo')

    # ### end Alembic commands ###
