"""add variante_proteina to platillos

Revision ID: c4da5367a4c9
Revises: b8f129f8a8b6
Create Date: 2026-07-22 18:44:19.797152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4da5367a4c9'
down_revision = 'b8f129f8a8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variante_proteina', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.drop_column('variante_proteina')

    # ### end Alembic commands ###
