"""alternativas globales via es_alternativa

Revision ID: edbbe9135712
Revises: aac3e73be391
Create Date: 2026-05-29 02:09:35.042054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbbe9135712'
down_revision = 'aac3e73be391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dia_alternativas')
    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternativa_plato_disponible', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('alternativa_bebida_disponible', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.drop_constraint(batch_op.f('dias_menu_alternativa_bebida_id_fkey'), type_='foreignkey')
        batch_op.drop_column('alternativa_bebida_id')

    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_alternativa', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platillos', schema=None) as batch_op:
        batch_op.drop_column('es_alternativa')

    with op.batch_alter_table('dias_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternativa_bebida_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('dias_menu_alternativa_bebida_id_fkey'), 'platillos', ['alternativa_bebida_id'], ['id'])
        batch_op.drop_column('alternativa_bebida_disponible')
        batch_op.drop_column('alternativa_plato_disponible')

    op.create_table('dia_alternativas',
    sa.Column('dia_menu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platillo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dia_menu_id'], ['dias_menu.id'], name=op.f('dia_alternativas_dia_menu_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillos.id'], name=op.f('dia_alternativas_platillo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dia_menu_id', 'platillo_id', name=op.f('dia_alternativas_pkey'))
    )
    # ### end Alembic commands ###
