"""entrega_direccion y entrega_referencias en pedido

Revision ID: fe4726ba53d1
Revises: 7b328f02f2eb
Create Date: 2026-06-03 00:03:43.613108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4726ba53d1'
down_revision = '7b328f02f2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega_direccion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entrega_referencias', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('entrega_referencias')
        batch_op.drop_column('entrega_direccion')

    # ### end Alembic commands ###
